version: '2'

services:
  webapp:
    restart: always
    image: quay.io/philbert/django-webapp:0.1.demo
    expose:
      - "8000"
    env_file: .env
    command: /usr/local/bin/gunicorn superlists.wsgi:application -w 2 -b :8000
  
  nginx:
    restart: always
    image: quay.io/philbert/django-nginx:0.1.1
    ports:
      - "80:80"
    volumes:
      - /www/static
    volumes_from:
      - webapp
    links:
      - webapp:superlists
  
  postgres:
    restart: always
    image: postgres:latest
    volumes_from:
      - data
    ports:
      - "5432:5432"
  
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
  
  data:
    restart: always
    image: postgres:latest
    volumes:
      - /var/lib/postgresql
    command: "true"
